### ISSUE TITLE
services/object-store missing ?

### ISSUE THREAD

**Issue by Vi-dot** [131/swift#1]
Hello,
Nice work, but where is this file ?
```
const storage = require('swift/services/object-store');
```

**Comment by Vi-dot** [comment]
My bad, I followed your second example in documentation and there is a mistake.
Should be replaced by
```
const storage = require('swift/storage');
```

**Comment by 131** [comment]
[Fixed](https://github.com/131/swift/commit/1fa792a6989ec4f7266653f35918a5f648a1e9e7) 👍
